# Site settings
title: Hello from Thnkr
name: Thnkr
email: hello@thnkr.co.uk
phone: 0123 3800 991
description: > # this means to ignore newlines until "baseurl:"
  Work with us to solve solutions for real people. Generating measurable value through innovative design and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thnkr.co.uk" # the base hostname & protocol for your site
twitter_username: teamThnkr
github_username:  team-thnkr

# Build settings
markdown: kramdown
