# Site settings
title: Space Between design and development house
name: Space Between
logo: /assets/images/spaceBetween.jpg
email: hello@spacebetween.io
phone: 01233 800991
description: >
  Hugely experienced web design and development house based in Kent. We design, build & grow your online experience with you, delivering measurable results.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spacebetween.io" # the base hostname & protocol for your site
themeColor: "#29abe2"

# Social
twitter_username: Space__Between
github_username: spacebetween
facebook_id: 1107841962590004
facebook_admin_ids: "[100007402451403,732802075]"

# Build settings
markdown: kramdown

collections:
  caseStudies:
    output: true
  process:
    output: true

gems:
  - jekyll-sitemap