# Site settings
title: Space Between design and development house
name: Space Between
email: hello@spacebetween.io
phone: 01233 800991
description: >
  Hugely experienced web design and development house based in Kent. We design, build & grow your online experience with you, delivering measurable results.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spacebetween.io" # the base hostname & protocol for your site
twitter_username: Space__Between
github_username:  spacebetween

# Build settings
markdown: kramdown

collections:
  caseStudies:
    output: true
  process:
    output: true

gems:
  - jekyll-sitemap